# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ResilienceMeasure_pb2 as ResilienceMeasure__pb2


class ResilienceMeasureStub(object):
    """The Dynamic Measure service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunDynamicMeasure = channel.unary_unary(
                '/ResilienceMeasure/RunDynamicMeasure',
                request_serializer=ResilienceMeasure__pb2.DynamicMeasureRequest.SerializeToString,
                response_deserializer=ResilienceMeasure__pb2.DynamicMeasureReply.FromString,
                )


class ResilienceMeasureServicer(object):
    """The Dynamic Measure service definition.
    """

    def RunDynamicMeasure(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResilienceMeasureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunDynamicMeasure': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDynamicMeasure,
                    request_deserializer=ResilienceMeasure__pb2.DynamicMeasureRequest.FromString,
                    response_serializer=ResilienceMeasure__pb2.DynamicMeasureReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResilienceMeasure', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResilienceMeasure(object):
    """The Dynamic Measure service definition.
    """

    @staticmethod
    def RunDynamicMeasure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResilienceMeasure/RunDynamicMeasure',
            ResilienceMeasure__pb2.DynamicMeasureRequest.SerializeToString,
            ResilienceMeasure__pb2.DynamicMeasureReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
