# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResilienceMeasure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResilienceMeasure.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17ResilienceMeasure.proto\":\n\x15\x44ynamicMeasureRequest\x12\x13\n\x0bmeasureType\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"&\n\x13\x44ynamicMeasureReply\x12\x0f\n\x07message\x18\x01 \x01(\t2X\n\x11ResilienceMeasure\x12\x43\n\x11RunDynamicMeasure\x12\x16.DynamicMeasureRequest\x1a\x14.DynamicMeasureReply\"\x00\x62\x06proto3'
)




_DYNAMICMEASUREREQUEST = _descriptor.Descriptor(
  name='DynamicMeasureRequest',
  full_name='DynamicMeasureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='measureType', full_name='DynamicMeasureRequest.measureType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='DynamicMeasureRequest.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=85,
)


_DYNAMICMEASUREREPLY = _descriptor.Descriptor(
  name='DynamicMeasureReply',
  full_name='DynamicMeasureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DynamicMeasureReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['DynamicMeasureRequest'] = _DYNAMICMEASUREREQUEST
DESCRIPTOR.message_types_by_name['DynamicMeasureReply'] = _DYNAMICMEASUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DynamicMeasureRequest = _reflection.GeneratedProtocolMessageType('DynamicMeasureRequest', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMICMEASUREREQUEST,
  '__module__' : 'ResilienceMeasure_pb2'
  # @@protoc_insertion_point(class_scope:DynamicMeasureRequest)
  })
_sym_db.RegisterMessage(DynamicMeasureRequest)

DynamicMeasureReply = _reflection.GeneratedProtocolMessageType('DynamicMeasureReply', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMICMEASUREREPLY,
  '__module__' : 'ResilienceMeasure_pb2'
  # @@protoc_insertion_point(class_scope:DynamicMeasureReply)
  })
_sym_db.RegisterMessage(DynamicMeasureReply)



_RESILIENCEMEASURE = _descriptor.ServiceDescriptor(
  name='ResilienceMeasure',
  full_name='ResilienceMeasure',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=215,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunDynamicMeasure',
    full_name='ResilienceMeasure.RunDynamicMeasure',
    index=0,
    containing_service=None,
    input_type=_DYNAMICMEASUREREQUEST,
    output_type=_DYNAMICMEASUREREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESILIENCEMEASURE)

DESCRIPTOR.services_by_name['ResilienceMeasure'] = _RESILIENCEMEASURE

# @@protoc_insertion_point(module_scope)
